### ISSUE TITLE
Chart alignment

### ISSUE THREAD

**Issue by delta1** [tari-project/block-explorer-frontend#115]
~~Could definitely be improved~~

In desktop, all three charts should be in a single row in this order: Historical Hash Rate, Network Difficulty, Circulating tXTR
On mobile, should be shown as one chart per row.

**Comment by c-franklin** [comment]
Could you post a screenshot of the issue?

**Comment by delta1** [comment]
I guess I don't have a solid suggestion at the moment. It might be nice on larger screens to have all 3 graphs in a single row. 

![image](https://user-images.githubusercontent.com/351403/108818535-33513f80-75c2-11eb-9dd3-48f0e88e9a1b.png)

**Comment by c-franklin** [comment]
ok - I can add some responsive flex containers to the scss library for this.

**Comment by stringhandler** [comment]
IMHO the Network difficulty and hash rate charts should have newest blocks on the right. They are currently on the left

**Comment by c-franklin** [comment]
> difficulty and hash rate charts should have newest blocks on the right. The

makes sense.

**Comment by delta1** [comment]
Hi @charlottefranklin we have updated the description text for this issue, if you still want to pick it up?

**Comment by c-franklin** [comment]
Yes great - sorry for radio silence - been absorbed in databases over the weekend! 
Will get onto it this week.

**Comment by c-franklin** [comment]
> ~Could definitely be improved~
> 
> In desktop, all three charts should be in a single row in this order: Historical Hash Rate, Network Difficulty, Circulating tXTR
> On mobile, should be shown as one chart per row.

Yep - can do this with flex and media query. 
Wanted to add the breakpoints to the sass vars too.

**Comment by delta1** [comment]
No problem, thanks!

**Comment by c-franklin** [comment]
> No problem, thanks!

Hello @delta1 getting on with this this week - was being optimistic last week. Cheers!

**Comment by c-franklin** [comment]
I am actually going to push this today.

**Comment by c-franklin** [comment]
- Have set up a flex scss file for all markup to access.
- Graphs all go on one line now. 
- There is a fixed width of 500 set in `EstimatedHashGraph.tx` so the third one jumps to the next line instead of being elastic width to a certain breakpoint (having an auto width would be nicer and that needs a proper grown up).

![image](https://user-images.githubusercontent.com/5900884/114493361-8a909980-9c6e-11eb-9ec1-3847e67dae79.png)

![image](https://user-images.githubusercontent.com/5900884/114493605-f115b780-9c6e-11eb-8603-317862b573dc.png)

**Comment by delta1** [comment]
Thanks @charlottefranklin that's great, please send a PR!
