### ISSUE TITLE
[QA] Main Chart / Hero

### ISSUE THREAD

**Issue by lsquaredleland** [tari-project/block-explorer-frontend#69]
- [ ] Set Max-Height: 800px (of the entire purple area). If possible increase the number of bars visible if a user has a super wide screen instead of making the individual bars a larger (after a certain amount ex: 4.5px)
- [ ] Tool-tip should show the value of the entire bar instead of each segment: 
  - [ ] XX time ago
  - [ ] XX block height
  - [ ] XX input(s)
  - [ ] XX outputs(s)
  - [ ] XX kernels(s)
  - [ ] XX Fees (if surfaced to the UI, no worries if that's not the case)
  - [ ] time to mine (believe this data is surfaced to the UI in order to do the spacing)

**Comment by coka** [comment]
Looking like:

- [ ] Set Max-Height: 800px (of the entire purple area). If possible increase the number of bars visible if a user has a super wide screen instead of making the individual bars a larger (after a certain amount ex: 4.5px)
- [x] Tool-tip should show the value of the entire bar instead of each segment:
  - [x] XX time ago
  - [x] XX block height
  - [x] XX input(s)
  - [x] XX outputs(s)
  - [x] XX kernels(s)
  - [x] XX Fees (if surfaced to the UI, no worries if that's not the case)
  - [x] time to mine (believe this data is surfaced to the UI in order to do the spacing)

I agree with spitting moar barz after they grow to 4.5px, but we would also need to know the absolute number of bars while they are growing in order to complete this requirement.

Alternatively, they could always be 4.5px, and then we would calculate however many fit for the given graph width.

**Comment by coka** [comment]
Looking like:

- [ ] Set Max-Height: 800px (of the entire purple area). If possible increase the number of bars visible if a user has a super wide screen instead of making the individual bars a larger (after a certain amount ex: 4.5px)
- [x] Tool-tip should show the value of the entire bar instead of each segment:
  - [x] XX time ago
  - [x] XX block height
  - [x] XX input(s)
  - [x] XX outputs(s)
  - [x] XX kernels(s)
  - [x] XX Fees (if surfaced to the UI, no worries if that's not the case)
  - [x] time to mine (believe this data is surfaced to the UI in order to do the spacing)

I agree with spitting moar barz after they grow to 4.5px, but we would also need to know the absolute number of bars while they are growing in order to complete this requirement.

Alternatively, they could always be 4.5px, and then we would calculate however many fit for the given graph width.
